### ISSUE TITLE
Cannot regenerate category path 

### ISSUE THREAD

**Issue by atty31** [elgentos/regenerate-catalog-urls#34]
Hi,
I am receiving the following error when I run the command: 
`bin/magento regenerate:category:path`

```
PHP Fatal error:  Uncaught Error: Call to a member function getBackend() on boolean in vendor/magento/module-eav/Model/Entity/AbstractEntity.php:1666
Stack trace:
#0 vendor/magento/module-catalog-url-rewrite/Observer/CategoryUrlPathAutogeneratorObserver.php(99): Magento\Eav\Model\Entity\AbstractEntity->saveAttribute(Object(Magento\Catalog\Model\Category\Interceptor), 'url_path')
#1 vendor/magento/module-catalog-url-rewrite/Observer/CategoryUrlPathAutogeneratorObserver.php(75): Magento\CatalogUrlRewrite\Observer\CategoryUrlPathAutogeneratorObserver->updateUrlKey(Object(Magento\Catalog\Model\Category\Interceptor), 'douche')
#2 vendor/magento/framework/Event/Invoker/InvokerDefault.php in vendor/magento/module-eav/Model/Entity/AbstractEntity.php on line 1666

```
I am running on version **0.2.4**  and my Magento version is 2.3.2   . Do you know why I am running into this error ? 

Thank you

**Comment by peterjaap** [comment]
Open up `vendor/magento/module-eav/Model/Entity/AbstractEntity.php`, go to line 1666 and dump out `$attributeCode`. Then check the `eav_attribute` table to see if this attribute exists and whether it is configured correctly.

**Comment by peterjaap** [comment]
Closed due to inactivity.
